plugins {
    id 'com.android.application'
}

android {
    namespace 'com.radio24online.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.radio24online.app'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
